# 02 — Phase 2 QLoRA training (Colab / cloud GPU)

Fine-tunes a classifier head on top of `google/gemma-4-E4B-it` using QLoRA (bnb 4-bit nf4). Vision and audio towers are dropped right after load so steady-state memory is text-only.

**Hardware**: needs CUDA. Don't run on Apple Silicon — bitsandbytes nf4 is CUDA-only. Use `01_smoke_test.ipynb` for any local Mac exploration.

**Recommended Colab tier**: A100 (40 GB) or A10. T4 (16 GB) is borderline — even after dropping vision/audio, the text tower at 4-bit + LoRA + activations is tight.

Tracks issue: https://github.com/Charlemagne-Labs/gateguard-suite/issues/73

## 1. Clone repo and install

Run these as shell cells (`!`-prefixed) the first time only.

In [1]:
# Skip if you've already cloned and installed in this Colab session.
import getpass
TOKEN = getpass.getpass("GitHub PAT (with repo scope): ")
!git clone https://staf-clabs:{TOKEN}@github.com/Charlemagne-Labs/g4h.git
%cd g4h
!pip install -q -e ".[train]"

GitHub PAT (with repo scope): ··········
Cloning into 'g4h'...
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 82 (delta 37), reused 70 (delta 25), pack-reused 0 (from 0)
Receiving objects: 100% (82/82), 47.63 KiB | 23.81 MiB/s, done.
Resolving deltas: 100% (37/37), done.
/content/g4h
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 41.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.6/10.6 MB 136.4 MB/s eta 0:00:00
  Building editable for g4h (pyproject.toml) ... done


## 2. Authenticate to Hugging Face

`google/gemma-4-E4B-it` is gated. Accept the license at https://huggingface.co/google/gemma-4-E4B-it then paste a read token below.

In [2]:
from huggingface_hub import login
login()  # paste token from https://huggingface.co/settings/tokens

## 3. Sanity checks

In [3]:
import torch
import transformers, peft, accelerate, bitsandbytes

assert torch.cuda.is_available(), "This notebook requires CUDA."
print(f"torch:        {torch.__version__}")
print(f"transformers: {transformers.__version__}")
print(f"peft:         {peft.__version__}")
print(f"accelerate:   {accelerate.__version__}")
print(f"bitsandbytes: {bitsandbytes.__version__}")
print(f"GPU:          {torch.cuda.get_device_name(0)}")
print(f"GPU memory:   {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

torch:        2.10.0+cu128
transformers: 5.8.0
peft:         0.19.1
accelerate:   1.13.0
bitsandbytes: 0.49.2
GPU:          NVIDIA A100-SXM4-40GB
GPU memory:   42.4 GB


## 4. Get the training data

We need `data/latest_ft_train_data.csv` (3259 rows, columns: `text`, `label`). Pick one path:

### Option A — manual upload (simplest)

1. Open the **Files** panel on the left side of Colab.
2. Navigate into `g4h/data/`.
3. Drag `latest_ft_train_data.csv` from your laptop into that directory.

Skip option B and run the verify cell below.

### Option B — pull from gateguard-suite (requires gh auth on Colab)

```python
!gh auth login --web --git-protocol https  # interactive
!gh repo clone Charlemagne-Labs/gateguard-suite -- --depth 1 --filter=blob:none --no-checkout /tmp/gg
!cd /tmp/gg && git sparse-checkout set data/latest_ft_train_data.csv && git checkout
!cp /tmp/gg/data/latest_ft_train_data.csv data/
```

In [4]:
# Verify the data is in place
import pandas as pd
from collections import Counter

CSV_PATH = "data/latest_ft_train_data.csv"
df = pd.read_csv(CSV_PATH)
print(f"rows: {len(df)}, cols: {list(df.columns)}")
print(f"label distribution: {dict(Counter(df['label']))}")
assert {'text', 'label'}.issubset(df.columns), "CSV must have text and label columns"
print("\nFirst row text (truncated):")
print("  " + str(df.iloc[0]['text'])[:200])

rows: 3259, cols: ['text', 'label']
label distribution: {1: 1252, 2: 959, 0: 1048}

First row text (truncated):
  url:ip_hostname:{"hostname":"45.141.87.195"} security:no_https:{"scheme":"http"}


## 5. QLoRA config + training

Defaults match the gateguard 270m-it baseline recipe. Change `cfg` fields if you want to sweep.

In [5]:
from transformers import BitsAndBytesConfig
from src.train import run_training, TrainConfig

bnb = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

cfg = TrainConfig(
    model_id="google/gemma-4-E4B-it",
    csv_path=CSV_PATH,
    out_dir="runs/gemma4-e4b-cls",
    val_ratio=0.10,
    test_ratio=0.10,
    max_length=256,
    epochs=3,
    batch=8,
    grad_accum=2,
    lr=2e-4,
    weight_decay=0.01,
    warmup_ratio=0.1,
    max_grad_norm=1.0,
    lora_r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    lora_target_modules=("q_proj", "k_proj", "v_proj", "o_proj",
                          "gate_proj", "up_proj", "down_proj"),
    use_class_weights=True,
    seed=42,
)

metrics = run_training(cfg, bnb_config=bnb)
print()
print("Final val metrics:")
for k, v in metrics.items():
    print(f"  {k}: {v:.4f}")

Device: cuda, dtype: torch.bfloat16
Split: 2611 train, 324 val, 324 test
Train label dist: {1: 1002, 2: 769, 0: 840}


config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/32.2M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/16.0G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/2076 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/208 [00:00<?, ?B/s]

[epoch 1] step 10 | lr 4.17e-05 | loss 2.1078
[epoch 1] step 20 | lr 8.33e-05 | loss 1.1660
[epoch 1] step 30 | lr 1.25e-04 | loss 0.5787
[epoch 1] step 40 | lr 1.67e-04 | loss 0.3555
[epoch 1] step 50 | lr 2.00e-04 | loss 0.2902
[epoch 1] step 60 | lr 2.00e-04 | loss 0.2598
[epoch 1] step 70 | lr 1.99e-04 | loss 0.1530
[epoch 1] step 80 | lr 1.97e-04 | loss 0.1564
[epoch 1] step 90 | lr 1.96e-04 | loss 0.0941
[epoch 1] step 100 | lr 1.93e-04 | loss 0.1077
[epoch 1] step 110 | lr 1.90e-04 | loss 0.0662
[epoch 1] step 120 | lr 1.87e-04 | loss 0.1516
[epoch 1] step 130 | lr 1.83e-04 | loss 0.2125
[epoch 1] step 140 | lr 1.79e-04 | loss 0.0429
[epoch 1] step 150 | lr 1.75e-04 | loss 0.1259
[epoch 1] step 160 | lr 1.70e-04 | loss 0.1432
[epoch 1] val: eval_loss=0.0485, eval_accuracy=0.9907, eval_f1_macro=0.9909
[epoch 2] step 170 | lr 1.65e-04 | loss 0.0422
[epoch 2] step 180 | lr 1.59e-04 | loss 0.0482
[epoch 2] step 190 | lr 1.53e-04 | loss 0.1162
[epoch 2] step 200 | lr 1.47e-04 | loss 

## 6. Inspect saved artifacts

In [6]:
import os
for root, dirs, files in os.walk(cfg.out_dir):
    level = root.replace(cfg.out_dir, '').count(os.sep)
    indent = '  ' * level
    print(f'{indent}{os.path.basename(root)}/')
    for f in files:
        size = os.path.getsize(os.path.join(root, f))
        print(f'{indent}  {f}  ({size:,} bytes)')

gemma4-e4b-cls/
  test_split.csv  (46,115 bytes)
  label_map.json  (142 bytes)
  tokenizer.json  (32,169,890 bytes)
  chat_template.jinja  (16,804 bytes)
  inference_config.json  (271 bytes)
  tokenizer_config.json  (2,742 bytes)
  classifier_head.pt  (32,741 bytes)
  base_lm/
    adapter_config.json  (1,219 bytes)
    README.md  (5,166 bytes)
    adapter_model.safetensors  (139,602,808 bytes)


Testing to see what happened

In [9]:
import torch, json
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel
from src.model import CausalLMWithClassifier, load_text_only_gemma4

OUT = "runs/gemma4-e4b-cls"
with open(f"{OUT}/inference_config.json") as f:
    cfg = json.load(f)
with open(f"{OUT}/label_map.json") as f:
    lm = json.load(f)
id2label = {int(k): v for k, v in lm["id2label"].items()}

bnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16,
                          bnb_4bit_quant_type="nf4", bnb_4bit_use_double_quant=True)
base = load_text_only_gemma4(cfg["base_model_id"], dtype=torch.bfloat16,
                              device_map={"": "cuda"}, bnb_config=bnb)
base = PeftModel.from_pretrained(base, f"{OUT}/base_lm")
model = CausalLMWithClassifier(base, num_labels=cfg["num_labels"]).to("cuda")
model.classifier.load_state_dict(torch.load(f"{OUT}/classifier_head.pt", map_location="cuda"))
model.eval()
print("Loaded.")

Loading weights:   0%|          | 0/2076 [00:00<?, ?it/s]

Loaded.


In [10]:
import pandas as pd
from collections import Counter

# 1. How many val rows have identical text in train?
df_all = pd.read_csv("data/latest_ft_train_data.csv")
# Reproduce the same split with the saved seed
from src.train import _stratified_split, _build_label_maps, _normalize_label
label2id, _ = _build_label_maps(("allow", "warn", "block"))
df_all["label_id"] = df_all["label"].apply(lambda x: _normalize_label(x, label2id))
train_df, val_df, test_df = _stratified_split(df_all, "label_id", 0.10, 0.10, 42)

train_texts = set(train_df["text"])
val_dups = sum(1 for t in val_df["text"] if t in train_texts)
test_dups = sum(1 for t in test_df["text"] if t in train_texts)
print(f"val rows with text identical to a train row: {val_dups}/{len(val_df)}")
print(f"test rows with text identical to a train row: {test_dups}/{len(test_df)}")

# 2. What does the dataset look like internally — how many unique texts?
print(f"\nTotal rows: {len(df_all)}")
print(f"Unique texts: {df_all['text'].nunique()}")
print(f"Duplication rate: {1 - df_all['text'].nunique() / len(df_all):.2%}")

# 3. Confusion matrix on val to see WHICH errors happen
import torch
from src.train import _evaluate, _tokenize, _TokenizedDataset
from torch.utils.data import DataLoader
from transformers import AutoTokenizer

# Reload to be safe (or use the model variable that's still in scope from training)
tok = AutoTokenizer.from_pretrained("runs/gemma4-e4b-cls")
val_enc = _tokenize(tok, val_df["text"].tolist(), 256)
val_ds = _TokenizedDataset(val_enc, torch.tensor(val_df["label_id"].tolist(), dtype=torch.long))
val_loader = DataLoader(val_ds, batch_size=8, shuffle=False)

# Get predictions
import numpy as np
all_preds, all_labels = [], []
model.eval()
with torch.no_grad():
    for batch in val_loader:
        batch = {k: v.to("cuda") for k, v in batch.items()}
        out = model(**batch)
        all_preds.append(torch.argmax(out.logits, dim=-1).cpu().numpy())
        all_labels.append(batch["labels"].cpu().numpy())
y_pred = np.concatenate(all_preds); y_true = np.concatenate(all_labels)

from sklearn.metrics import confusion_matrix, classification_report
print("\nConfusion matrix (rows=true, cols=pred), order [allow, warn, block]:")
print(confusion_matrix(y_true, y_pred))
print("\nPer-class report:")
print(classification_report(y_true, y_pred, target_names=["allow", "warn", "block"]))

val rows with text identical to a train row: 75/324
test rows with text identical to a train row: 59/324

Total rows: 3259
Unique texts: 2674
Duplication rate: 17.95%

Confusion matrix (rows=true, cols=pred), order [allow, warn, block]:
[[104   0   0]
 [  0 125   0]
 [  0   2  93]]

Per-class report:
              precision    recall  f1-score   support

       allow       1.00      1.00      1.00       104
        warn       0.98      1.00      0.99       125
       block       1.00      0.98      0.99        95

    accuracy                           0.99       324
   macro avg       0.99      0.99      0.99       324
weighted avg       0.99      0.99      0.99       324



## 7. Package for download

Tarball the run directory so you can download it from Colab in one click. The output shape matches gateguard's `inference_config.json` schema, so this tarball can be uploaded to `charley-s3-teacher-model` as `teacher_model.tar.gz` and consumed by `Charlemagne-Labs/test_suite/phase2`.

In [7]:
import tarfile
tarball = f"{cfg.out_dir.rstrip('/')}.tar.gz"
with tarfile.open(tarball, "w:gz") as t:
    t.add(cfg.out_dir, arcname=os.path.basename(cfg.out_dir))
print(f"Wrote {tarball} ({os.path.getsize(tarball):,} bytes)")
print("Right-click the file in the Colab Files panel and pick 'Download'.")

Wrote runs/gemma4-e4b-cls.tar.gz (134,678,754 bytes)
Right-click the file in the Colab Files panel and pick 'Download'.
